<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260524120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Gamification: badges, attributions, préférences profil, vues activités';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE badge_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT NOT NULL, image_url VARCHAR(512) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, is_hidden_by_default BOOLEAN DEFAULT false NOT NULL, rule_type VARCHAR(32) NOT NULL, rule_config JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BADGE_CODE ON badge_definition (code)');

        $this->addSql('CREATE TABLE user_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlocked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_badge ON user_badge (user_id, badge_id)');
        $this->addSql('CREATE INDEX IDX_USER_BADGE_USER ON user_badge (user_id)');
        $this->addSql('CREATE INDEX IDX_USER_BADGE_BADGE ON user_badge (badge_id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_USER_BADGE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_USER_BADGE_BADGE FOREIGN KEY (badge_id) REFERENCES badge_definition (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE user_badge_display (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_displayed_on_profile BOOLEAN DEFAULT true NOT NULL, display_order INT DEFAULT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_badge_display ON user_badge_display (user_id, badge_id)');
        $this->addSql('ALTER TABLE user_badge_display ADD CONSTRAINT FK_USER_BADGE_DISPLAY_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge_display ADD CONSTRAINT FK_USER_BADGE_DISPLAY_BADGE FOREIGN KEY (badge_id) REFERENCES badge_definition (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE user_activity_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_activity_view ON user_activity_view (user_id, activity_id)');
        $this->addSql('ALTER TABLE user_activity_view ADD CONSTRAINT FK_USER_ACTIVITY_VIEW_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_activity_view ADD CONSTRAINT FK_USER_ACTIVITY_VIEW_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE "user" ADD hide_badges_on_profile BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" DROP hide_badges_on_profile');
        $this->addSql('ALTER TABLE user_activity_view DROP CONSTRAINT FK_USER_ACTIVITY_VIEW_ACTIVITY');
        $this->addSql('ALTER TABLE user_activity_view DROP CONSTRAINT FK_USER_ACTIVITY_VIEW_USER');
        $this->addSql('DROP TABLE user_activity_view');
        $this->addSql('ALTER TABLE user_badge_display DROP CONSTRAINT FK_USER_BADGE_DISPLAY_BADGE');
        $this->addSql('ALTER TABLE user_badge_display DROP CONSTRAINT FK_USER_BADGE_DISPLAY_USER');
        $this->addSql('DROP TABLE user_badge_display');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_USER_BADGE_BADGE');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_USER_BADGE_USER');
        $this->addSql('DROP TABLE user_badge');
        $this->addSql('DROP TABLE badge_definition');
    }
}
