<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260401120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Comments on activities, per-user ratings, denormalized aggregates on activity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE activity ADD rating_average NUMERIC(4, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD rating_count INT DEFAULT 0 NOT NULL');

        $this->addSql('CREATE TABLE comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_edited BOOLEAN DEFAULT false NOT NULL, is_hidden BOOLEAN DEFAULT false NOT NULL, author_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_comment_activity_created ON comments (activity_id, created_at)');
        $this->addSql('CREATE INDEX idx_comment_user_created ON comments (author_id, created_at)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_comments_author FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_comments_activity FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE activity_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_activity_rating ON activity_rating (user_id, activity_id)');
        $this->addSql('ALTER TABLE activity_rating ADD CONSTRAINT FK_activity_rating_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity_rating ADD CONSTRAINT FK_activity_rating_activity FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE activity_rating DROP CONSTRAINT FK_activity_rating_activity');
        $this->addSql('ALTER TABLE activity_rating DROP CONSTRAINT FK_activity_rating_user');
        $this->addSql('DROP TABLE activity_rating');

        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_comments_activity');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_comments_author');
        $this->addSql('DROP TABLE comments');

        $this->addSql('ALTER TABLE activity DROP rating_average');
        $this->addSql('ALTER TABLE activity DROP rating_count');
    }
}
