<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260323170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create admin_audit_log table for admin action traceability';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admin_email VARCHAR(180) DEFAULT NULL, action VARCHAR(20) NOT NULL, entity_class VARCHAR(255) NOT NULL, entity_id VARCHAR(64) DEFAULT NULL, level VARCHAR(20) NOT NULL, summary VARCHAR(500) NOT NULL, context JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_40CEDA5AB03A8386 ON admin_audit_log (created_at)');
        $this->addSql('CREATE INDEX IDX_40CEDA5AA76ED395 ON admin_audit_log (admin_email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_audit_log');
    }
}
