<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260320110500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create admin_webauthn_credential table for admin passkeys';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_webauthn_credential (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, credential_id VARCHAR(255) NOT NULL, credential_source TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E7E9E8B94431CA4D ON admin_webauthn_credential (credential_id)');
        $this->addSql('CREATE INDEX IDX_E7E9E8B9A76ED395 ON admin_webauthn_credential (user_id)');
        $this->addSql('ALTER TABLE admin_webauthn_credential ADD CONSTRAINT FK_E7E9E8B9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_webauthn_credential');
    }
}
