<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260525140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Exploration carte: cellules visitées par utilisateur + consentement GPS';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_map_cell (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cell_id VARCHAR(16) NOT NULL, zone_key VARCHAR(32) NOT NULL, first_visited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_visited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_map_cell ON user_map_cell (user_id, cell_id)');
        $this->addSql('CREATE INDEX IDX_USER_MAP_CELL_USER ON user_map_cell (user_id)');
        $this->addSql('ALTER TABLE user_map_cell ADD CONSTRAINT FK_USER_MAP_CELL_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD map_exploration_consent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" DROP map_exploration_consent_at');
        $this->addSql('ALTER TABLE user_map_cell DROP CONSTRAINT FK_USER_MAP_CELL_USER');
        $this->addSql('DROP TABLE user_map_cell');
    }
}
